In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import json
import requests
from pandas.io.json import json_normalize
from sklearn.cluster import KMeans
import folium
import regex as re
import pgeocode

In [2]:
# loading neighborhood data
df = pd.read_csv("../data/Geospatial_Coordinates.csv")

In [3]:
df

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [4]:
import wikipedia as wp

In [19]:
# finding neighborhood names from wikipedia
html = wp.page("List of postal codes of Canada: M").html().encode("UTF-8")
df_wiki = pd.read_html(html)[0]

In [6]:
df_wiki.head()

,0,1,2,3,4,5,6,7,8
0,M1A Not assigned,M2A Not assigned,M3A North York (Parkwoods),M4A North York (Victoria Village),M5A Downtown Toronto (Regent Park / Harbourfront),M6A North York (Lawrence Manor / Lawrence Heig...,M7A Queen's Park (Ontario Provincial Government),M8A Not assigned,M9A Etobicoke (Islington Avenue)
1,M1B Scarborough (Malvern / Rouge),M2B Not assigned,M3B North York (Don Mills) North,M4B East York (Parkview Hill / Woodbine Gardens),"M5B Downtown Toronto (Garden District, Ryerson)",M6B North York (Glencairn),M7B Not assigned,M8B Not assigned,M9B Etobicoke (West Deane Park / Princess Gard...
2,M1C Scarborough (Rouge Hill / Port Union / Hig...,M2C Not assigned,M3C North York (Don Mills) South (Flemingdon P...,M4C East York (Woodbine Heights),M5C Downtown Toronto (St. James Town),M6C York (Humewood-Cedarvale),M7C Not assigned,M8C Not assigned,M9C Etobicoke (Eringate / Bloordale Gardens / ...
3,M1E Scarborough (Guildwood / Morningside / Wes...,M2E Not assigned,M3E Not assigned,M4E East Toronto (The Beaches),M5E Downtown Toronto (Berczy Park),M6E York (Caledonia-Fairbanks),M7E Not assigned,M8E Not assigned,M9E Not assigned
4,M1G Scarborough (Woburn),M2G Not assigned,M3G Not assigned,M4G East York (Leaside),M5G Downtown Toronto (Central Bay Street),M6G Downtown Toronto (Christie),M7G Not assigned,M8G Not assigned,M9G Not assigned

In [9]:
# The neighborhood names are provided inside the brackets, we need to extract them and the corresponding postal code
from data_processing.functions import extract_neighborhood_name
df_hoods = extract_neighborhood_name(df_wiki)
df_hoods.head()

  Postal Code               neighbourhood
0         M1A             M1A Not assigne
1         M2A             M2A Not assigne
2         M3A                   Parkwoods
3         M4A            Victoria Village
4         M5A  Regent Park / Harbourfront

In [10]:
# Merge both dataframes and drop any neighbourhoods we dont have lat and lon coordinates for
df_neighbourhoods = df.merge(df_hoods, on='Postal Code', how='left')
df_neighbourhoods.head()

  Postal Code   Latitude  Longitude                             neighbourhood
0         M1B  43.806686 -79.194353                           Malvern / Rouge
1         M1C  43.784535 -79.160497  Rouge Hill / Port Union / Highland Creek
2         M1E  43.763573 -79.188711       Guildwood / Morningside / West Hill
3         M1G  43.770992 -79.216917                                    Woburn
4         M1H  43.773136 -79.239476                                 Cedarbrae

In [18]:
df_neighbourhoods.to_csv('../data/df_neighbourhoods.csv', index=False)